[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["venv", ".venv", "__pycache__", ".git", "dist", "build", "tests"]
