services:
  - type: worker
    name: cursor-monitor
    env: python
    plan: starter    # Worker דורש Starter plan. אם אתה רוצה להריץ ב-Free, צריך להפוך ל-Web Service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
